export const TAG_LIST_REQUEST = "TAG_LIST_REQUEST";
export const TAG_LIST_SUCCESS = "TAG_LIST_SUCCESS";
export const TAG_LIST_FAIL = "TAG_LIST_FAIL";

export const TAG_DETAIL_REQUEST = "TAG_DETAIL_REQUEST";
export const TAG_DETAIL_SUCCESS = "TAG_DETAIL_SUCCESS";
export const TAG_DETAIL_FAIL = "TAG_DETAIL_FAIL";
